name: Deploy Lambda

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # OIDC ç”¨
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_USER_ID }}:role/github-terraform-role
          aws-region: ap-northeast-1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Build Lambda ZIP
        run: |
          pip install -r requirements.txt -t package/
          cp main.py package/
          cd package
          zip -r ../lambda.zip .
          cd ..

      - name: Terraform Init & Apply
        run: |
          terraform init
          terraform apply -auto-approve
